name: Check code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
      - name: Install pre-commit hooks
        run: |
          pre-commit install
      - name: Run pre-commit
        run: |
          pre-commit run -a
